### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Wolf727** [evolution-project/evolution#4]
![image](https://user-images.githubusercontent.com/97886897/151717796-8ce8a44a-5fc1-4a94-aeea-93d8911fc7a9.png)

**Comment by evolution-project** [comment]
do u read what daemon say when u type `status` ? NO it clear say `not mining` now pls move the conversation on the original repo 
https://github.com/evolution-project/evolution

**Comment by evolution-project** [comment]
oh ok i now saw u moved, so that is a test repo , now close this coz u get the wrong repo

**Comment by Wolf727** [comment]
this is wrong repo? a? im get release from THIS repo

**Comment by Wolf727** [comment]
your daemon have miner on your wallet

**Comment by evolution-project** [comment]
this is official repo is ok is good u can download the latest from here, and yes the daemon have miner in is normal this thing, btw what are  u try to do ?
